<a href="https://colab.research.google.com/github/osmanyener/TensorFlow/blob/main/Tensorflow_Mod1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%tensorflow_version 2.x
import tensorflow as tf
print(tf.version)

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.
<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.10/dist-packages/tensorflow/_api/v2/version/__init__.py'>


In [2]:
string = tf.Variable("starting to ML",tf.string)
number = tf.Variable(375, tf.int16)
floating = tf.Variable(3.5452, tf.float64)

What we have created above is tensor of rank 0, also known as a scalar. Now, lets create some tensors of higher degrees or/ranks.

In [12]:
rank1_tensor = tf.Variable(["Test", "Ok", "Tim","k"], tf.string)
rank2_tensor = tf.Variable([["test", "ok","ok","ok"], ["john", "bob","lik","then"]], tf.string)

in the first line, we have one array so its rank is 1. But in the second line, there are two dimensional array in the list so its rank would be 2. Now, lets try to execute tensors.  

In [13]:
tf.rank(rank1_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [15]:
rank2_tensor.shape

TensorShape([2, 4])

The shape of a tensor is simply the amount of elements that exist in each dimension. For example which is above, the shape of rank2_tensor is ([2,4]) which means there are two list and there are 4 item inside of the each list.

## Changing Shape


The number of elements of a tensor is the product of the sizes of all its shapes.

In [16]:
tensor1 = tf.ones([1,2,3])              # tf.ones() create a shape [1,2,3] tensor full of ones
tensor2 = tf.reshape(tensor1,[2,3,1])   # reshape existing data to shape [2,3,1]
tensor3 = tf.reshape(tensor2,[3,-1])    # -1 tells the tensor to calculate the size of the dimension in that place
                                        # this wlil reshape the tensor [3,2]
                                        # the number of elements in the reshaped tensor MUST match the number in the original

In [17]:
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [ ]:
# Example of changing the shape
t = tf.zeros([5,5,5,5])
# print(t)
t2 = tf.reshape(t,[625])
# print(t2)
t3 = tf.reshape(t2,[125,-1])
print(t3)